//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cal.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//

package polynomial;


public class cal {
    public String Command;
    public String Var;
    public int Val;
    public int Ill_flag;
    public String Expression;
    public void Check_cmd() {
    
    }
    
    public String cmd_pro(Object String, int flag) {
    
    		String s=null;
    		return s;
    }
    
    public void Expression_pro() {
    
    }
}
