//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : derivation.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//




public class derivation extends cal {
    public String cmd_pro(Object String, Object int&) {
    
    }
}
