//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : expression.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//




public class expression {
    private String Expression;
    private String Expre;
    private int Illegal_flag;
    private String Proedexp;
    private void Check_exp() {
    
    }
    
    public String Expre_pro(Object String, Object int&) {
    
    }
}
