//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : processexpclass.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//




public class processexpclass {
    private String Expression;
    private String Command;
    private int CmdFlag;
    private String Out_exp;
    private int Bug_flag;
    private void Check_in() {
    
    }
    
    private void CheckBug() {
    
    }
    
    public String ProcessExp(Object String, Object int&) {
    
    }
}
