//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : simplify.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//

package polynomial;


public class simplify extends cal {
    public String cmd_pro(Object String, Object int&) {
    
    }
}
