//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : userclass.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//

package polynomial;


public class userclass {
    private String Input_str;
    private String Output_str;
    public void Input() {
    
    }
    
    public void Output() {
    
    }
    
    private void ProcessExp() {
    
    }
}
